"""
Learning Guide Generation Module (Template Filling)

Generates a Learning Guide (LG) document by populating a DOCX template
with course content. Expects Course_Overview and LO_Description to be
pre-generated in the context dict by Claude Code skill.

No API calls are made from this module.
"""

import json
import tempfile
from docxtpl import DocxTemplate
from generate_ap_fg_lg_lp.utils.helper import process_logo_image

LG_TEMPLATE_DIR = ".claude/skills/generate_learner_guide/templates/LG_TGS-Ref-No_Course-Title_v1.docx"


def generate_learning_guide(context: dict, name_of_organisation: str) -> str:
    """
    Generates a Learning Guide document by populating a DOCX template with course content.

    Expects context to already contain 'Course_Overview' and 'LO_Description' keys
    (pre-generated by Claude Code skill). If missing, uses placeholder text.

    Args:
        context: Dictionary containing course details including Course_Overview and LO_Description.
        name_of_organisation: Organization name for branding.

    Returns:
        File path of the generated Learning Guide document.
    """
    # Ensure Course_Overview and LO_Description are present
    if not context.get("Course_Overview"):
        course_title = context.get("Course_Title", "this course")
        context["Course_Overview"] = f"The {course_title} course provides comprehensive training in the key concepts and skills required for professional competency. [Run Claude Code skill /generate_courseware to generate full content]"

    if not context.get("LO_Description"):
        context["LO_Description"] = "By the end of this course, learners will be able to apply the knowledge and skills covered. [Run Claude Code skill /generate_courseware to generate full content]"

    # Validate and normalize Learning_Units structure for template
    learning_units = context.get("Learning_Units", [])
    if not isinstance(learning_units, list):
        learning_units = []

    validated_learning_units = []
    for i, lu in enumerate(learning_units):
        if not isinstance(lu, dict):
            continue

        validated_lu = {
            "LU_Title": lu.get("LU_Title", f"Learning Unit {i+1}"),
            "LO": lu.get("LO", ""),
            "Topics": lu.get("Topics", []),
            "K_numbering_description": lu.get("K_numbering_description", []),
            "A_numbering_description": lu.get("A_numbering_description", []),
            "Assessment_Methods": lu.get("Assessment_Methods", []),
            "Instructional_Methods": lu.get("Instructional_Methods", []),
        }

        # Validate nested structures
        validated_topics = []
        for topic in validated_lu["Topics"]:
            if isinstance(topic, dict):
                validated_topics.append({
                    "Topic_Title": topic.get("Topic_Title", ""),
                    "Bullet_Points": topic.get("Bullet_Points", [])
                })
        validated_lu["Topics"] = validated_topics

        validated_k = []
        for k in validated_lu["K_numbering_description"]:
            if isinstance(k, dict):
                validated_k.append({"K_number": k.get("K_number", ""), "Description": k.get("Description", "")})
        validated_lu["K_numbering_description"] = validated_k

        validated_a = []
        for a in validated_lu["A_numbering_description"]:
            if isinstance(a, dict):
                validated_a.append({"A_number": a.get("A_number", ""), "Description": a.get("Description", "")})
        validated_lu["A_numbering_description"] = validated_a

        validated_learning_units.append(validated_lu)

    context["Learning_Units"] = validated_learning_units

    doc = DocxTemplate(LG_TEMPLATE_DIR)

    # Add the logo and organization details to the context
    context['company_logo'] = process_logo_image(doc, name_of_organisation)
    context['Name_of_Organisation'] = name_of_organisation

    # Ensure UEN is set from organization data
    from generate_ap_fg_lg_lp.utils.organizations import get_organizations, get_default_organization
    organizations = get_organizations()
    org = next((o for o in organizations if o["name"] == name_of_organisation), None)
    if org and org.get("uen"):
        context['UEN'] = org["uen"]
    else:
        default_org = get_default_organization()
        if default_org.get("uen"):
            context['UEN'] = default_org["uen"]

    # Add Document Version Control Record data
    from datetime import datetime
    current_date = datetime.now().strftime("%d %b %Y")
    context['Rev_No'] = "1.0"
    context['Effective_Date'] = current_date
    context['Author'] = ""
    context['Reviewed_By'] = ""
    context['Approved_By'] = ""

    # Prepare Assessment Summary with abbreviated assessment methods
    assessment_summary = []
    method_abbreviations = {
        "Written Assessment - Short Answer Questions": "WA-SAQ",
        "Written Assessment": "WA",
        "Written Exam": "WA-SAQ",
        "Practical Performance": "PP",
        "Practical Exam": "PP",
        "Case Study": "CS",
        "Oral Questioning": "OQ",
        "Role Play": "RP",
        "Project": "PJ",
        "Portfolio": "PF",
        "Observation": "OB",
    }

    for lu in validated_learning_units:
        lo_full = lu.get("LO", "")
        assessment_methods = lu.get("Assessment_Methods", [])
        abbreviated_methods = []
        for method in assessment_methods:
            if method in ["WA-SAQ", "WA", "PP", "CS", "OQ", "RP", "PJ", "PF", "OB"]:
                abbreviated_methods.append(method)
            else:
                abbr = method_abbreviations.get(method, method)
                if abbr == method and len(method) > 5:
                    words = method.split()
                    abbr = "-".join([w[0].upper() for w in words if w[0].isupper() or w == words[0]])
                abbreviated_methods.append(abbr)

        assessment_summary.append({
            "LO": lo_full,
            "Assessment_Methods": ", ".join(abbreviated_methods)
        })

    context['Assessment_Summary'] = assessment_summary

    # Also update Learning_Units to have abbreviated assessment methods
    for i, lu in enumerate(validated_learning_units):
        assessment_methods = lu.get("Assessment_Methods", [])
        abbreviated_methods = []
        for method in assessment_methods:
            if method in ["WA-SAQ", "WA", "PP", "CS", "OQ", "RP", "PJ", "PF", "OB"]:
                abbreviated_methods.append(method)
            else:
                abbr = method_abbreviations.get(method, method)
                if abbr == method and len(method) > 5:
                    words = method.split()
                    abbr = "-".join([w[0].upper() for w in words if w[0].isupper() or w == words[0]])
                abbreviated_methods.append(abbr)
        context['Learning_Units'][i]['Assessment_Methods_Abbr'] = ", ".join(abbreviated_methods)

    doc.render(context, autoescape=True)
    with tempfile.NamedTemporaryFile(delete=False, suffix=".docx") as tmp_file:
        doc.save(tmp_file.name)
        output_path = tmp_file.name

    return output_path
